In [2]:
import pandas as pd

coffee = pd.read_csv('./warmup-data/coffee.csv')

In [3]:
ss = coffee.size
coffee.sample(10)

          Day Coffee Type  Units Sold
6    Thursday    Espresso          40
0      Monday    Espresso          25
11   Saturday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
3     Tuesday       Latte          20
8      Friday    Espresso          45
1      Monday       Latte          15
5   Wednesday       Latte          25
2     Tuesday    Espresso          30

In [4]:
results = pd.read_parquet('./data/results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [5]:
olympics = pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [ ]:
bios = pd.read_csv('./data/bios.csv')
bios.head()
bios[bios['born_country']=='MEX'], ['name','born_country']

(        athlete_id                 name   born_date  \
 222            223     László Markovits  1970-04-04
 795            799         Ilana Berger  1965-12-31
 964            968      Félix del Canto  1893-06-21
 965            969  Alejandro Hernández  1977-10-01
 966            970     Leonardo Lavalle  1967-07-14
 ...            ...                  ...         ...
 141749      145330      Duilio Carrillo  1997-03-24
 141757      145338       Jonathan Muñoz  1995-11-10
 144105      147775      Édgar Arredondo  1997-05-16
 144107      147777      Fabián Anguamea  1993-12-21
 144947      148656     Donovan Carrillo  1999-11-17

                              born_city       born_region born_country  \
 222     Ciudad de México (Mexico City)  Ciudad de México          MEX
 795     Ciudad de México (Mexico City)  Ciudad de México          MEX
 964                             Puebla            Puebla          MEX
 965                            Tijuana   Baja California          MEX
 966     Ciudad de México (Mexico City)  Ciudad de México          MEX
 ...                                ...               ...          ...
 141749                     Guadalajara           Jalisco          MEX
 141757                  Aguascalientes    Aguascalientes          MEX
 144105                        Culiacán           Sinaloa          MEX
 144107                  Ciudad Obregón            Sonora          MEX
 144947                         Zapopan           Jalisco          MEX

             NOC  height_cm  weight_kg   died_date
 222     Hungary      180.0       80.0         NaN
 795      Israel      169.0       63.0         NaN
 964      Mexico      168.0        NaN  1962-01-29
 965      Mexico      180.0       76.0         NaN
 966      Mexico      188.0       79.0         NaN
 ...         ...        ...        ...         ...
 141749   Mexico        NaN        NaN         NaN
 141757   Mexico      163.0       67.0         NaN
 144105   Mexico      190.0        NaN         NaN
 144107   Mexico      188.0        NaN         NaN
 144947   Mexico        NaN        NaN         NaN

 [1177 rows x 10 columns],
 ['name', 'born_country'])

In [21]:
olymp_ids = olympics['athlete_id'].unique()
mask = bios['athlete_id'].isin(olymp_ids) & (
    (bios['born_region'] == 'New Hampshire') | (bios['born_city'] == 'San Francisco')
)
bios_olympians = bios.loc[mask, ['athlete_id', 'name', 'born_city', 'born_region', 'born_country', 'height_cm', 'weight_kg']]
bios_olympians.sort_values('born_region').tail()

,athlete_id,name,born_city,born_region,born_country,height_cm,weight_kg
133387,136326,Alex Karwoski,Nashua,New Hampshire,USA,193.0,91.0
135130,138272,Patrick Caldwell,Lebanon,New Hampshire,USA,183.0,77.0
135213,138360,Will Rhoads,Concord,New Hampshire,USA,188.0,69.0
135958,139174,Hunter Henderson,Portsmouth,New Hampshire,USA,NaN,NaN
144449,148141,Elese Sommerová,Dover,New Hampshire,USA,NaN,NaN

In [67]:
import numpy as np
coffee['new_price'] = np.where(coffee["Coffee Type"] == 'Espresso', 3.99, 5.80)
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.80
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.80
4  Wednesday    Espresso          35       3.99

In [62]:
bios.loc[bios['born_country']=='MEX', ['name','born_country', 'height_cm', 'weight_kg']]

                       name born_country  height_cm  weight_kg
222        László Markovits          MEX      180.0       80.0
795            Ilana Berger          MEX      169.0       63.0
964         Félix del Canto          MEX      168.0        NaN
965     Alejandro Hernández          MEX      180.0       76.0
966        Leonardo Lavalle          MEX      188.0       79.0
...                     ...          ...        ...        ...
141749      Duilio Carrillo          MEX        NaN        NaN
141757       Jonathan Muñoz          MEX      163.0       67.0
144105      Édgar Arredondo          MEX      190.0        NaN
144107      Fabián Anguamea          MEX      188.0        NaN
144947     Donovan Carrillo          MEX        NaN        NaN

[1177 rows x 4 columns]